# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 619)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(454, 619))
        MainWindow.setMaximumSize(QtCore.QSize(454, 619))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../assets/app-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: #f9f9f9;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 740, 614))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.main_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_layout.setContentsMargins(16, 16, 16, 16)
        self.main_layout.setSpacing(16)
        self.main_layout.setObjectName("main_layout")
        self.form_layout = QtWidgets.QVBoxLayout()
        self.form_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.form_layout.setSpacing(0)
        self.form_layout.setObjectName("form_layout")
        self.invisible_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invisible_label.sizePolicy().hasHeightForWidth())
        self.invisible_label.setSizePolicy(sizePolicy)
        self.invisible_label.setMinimumSize(QtCore.QSize(264, 0))
        self.invisible_label.setMaximumSize(QtCore.QSize(264, 0))
        self.invisible_label.setStyleSheet("")
        self.invisible_label.setText("")
        self.invisible_label.setObjectName("invisible_label")
        self.form_layout.addWidget(self.invisible_label)
        self.lineedits_layout = QtWidgets.QVBoxLayout()
        self.lineedits_layout.setContentsMargins(-1, -1, -1, 8)
        self.lineedits_layout.setSpacing(8)
        self.lineedits_layout.setObjectName("lineedits_layout")
        self.name_layout = QtWidgets.QVBoxLayout()
        self.name_layout.setSpacing(4)
        self.name_layout.setObjectName("name_layout")
        self.name_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.name_label.setStyleSheet("padding-left: 2px;\n"
"color: #5a5a5a;")
        self.name_label.setObjectName("name_label")
        self.name_layout.addWidget(self.name_label)
        self.name_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lineedit.sizePolicy().hasHeightForWidth())
        self.name_lineedit.setSizePolicy(sizePolicy)
        self.name_lineedit.setMinimumSize(QtCore.QSize(0, 0))
        self.name_lineedit.setStyleSheet("width: 400px;\n"
"height: 30px;\n"
"background-color: #e9e9e9;\n"
"border: 1px solid #828282;\n"
"border-radius: 8px;\n"
"font-family: Montserrat, sans-serif;\n"
"font-size: 1.3rem;\n"
"outline: none;\n"
"padding: 0 6px;")
        self.name_lineedit.setText("")
        self.name_lineedit.setObjectName("name_lineedit")
        self.name_layout.addWidget(self.name_lineedit)
        self.name_error_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.name_error_label.setStyleSheet("padding-left: 2px;\n"
"color: #a10e0e;")
        self.name_error_label.setObjectName("name_error_label")
        self.name_layout.addWidget(self.name_error_label)
        self.lineedits_layout.addLayout(self.name_layout)
        self.surname_layout = QtWidgets.QVBoxLayout()
        self.surname_layout.setSpacing(4)
        self.surname_layout.setObjectName("surname_layout")
        self.surname_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.surname_label.setStyleSheet("padding-left: 2px;\n"
"color: #5a5a5a;")
        self.surname_label.setObjectName("surname_label")
        self.surname_layout.addWidget(self.surname_label)
        self.surname_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surname_lineedit.sizePolicy().hasHeightForWidth())
        self.surname_lineedit.setSizePolicy(sizePolicy)
        self.surname_lineedit.setMinimumSize(QtCore.QSize(0, 0))
        self.surname_lineedit.setStyleSheet("width: 400px;\n"
"height: 30px;\n"
"background-color: #e9e9e9;\n"
"border: 1px solid #828282;\n"
"border-radius: 8px;\n"
"font-family: Montserrat, sans-serif;\n"
"font-size: 1.3rem;\n"
"outline: none;\n"
"padding: 0 6px;")
        self.surname_lineedit.setText("")
        self.surname_lineedit.setObjectName("surname_lineedit")
        self.surname_layout.addWidget(self.surname_lineedit)
        self.surname_error_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.surname_error_label.setStyleSheet("padding-left: 2px;\n"
"color: #a10e0e;")
        self.surname_error_label.setObjectName("surname_error_label")
        self.surname_layout.addWidget(self.surname_error_label)
        self.lineedits_layout.addLayout(self.surname_layout)
        self.phone_layout = QtWidgets.QVBoxLayout()
        self.phone_layout.setSpacing(4)
        self.phone_layout.setObjectName("phone_layout")
        self.phone_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.phone_label.setStyleSheet("padding-left: 2px;\n"
"color: #5a5a5a;")
        self.phone_label.setObjectName("phone_label")
        self.phone_layout.addWidget(self.phone_label)
        self.phone_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_lineedit.sizePolicy().hasHeightForWidth())
        self.phone_lineedit.setSizePolicy(sizePolicy)
        self.phone_lineedit.setMinimumSize(QtCore.QSize(0, 0))
        self.phone_lineedit.setStyleSheet("width: 400px;\n"
"height: 30px;\n"
"background-color: #e9e9e9;\n"
"border: 1px solid #828282;\n"
"border-radius: 8px;\n"
"font-family: Montserrat, sans-serif;\n"
"font-size: 1.3rem;\n"
"outline: none;\n"
"padding: 0 6px;")
        self.phone_lineedit.setInputMask("")
        self.phone_lineedit.setText("")
        self.phone_lineedit.setObjectName("phone_lineedit")
        self.phone_layout.addWidget(self.phone_lineedit)
        self.phone_error_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.phone_error_label.setEnabled(True)
        self.phone_error_label.setStyleSheet("padding-left: 2px;\n"
"color: #a10e0e;")
        self.phone_error_label.setObjectName("phone_error_label")
        self.phone_layout.addWidget(self.phone_error_label)
        self.lineedits_layout.addLayout(self.phone_layout)
        self.email_layout = QtWidgets.QVBoxLayout()
        self.email_layout.setSpacing(4)
        self.email_layout.setObjectName("email_layout")
        self.email_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.email_label.setEnabled(True)
        self.email_label.setStyleSheet("padding-left: 2px;\n"
"color: #5a5a5a;")
        self.email_label.setObjectName("email_label")
        self.email_layout.addWidget(self.email_label)
        self.email_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_lineedit.sizePolicy().hasHeightForWidth())
        self.email_lineedit.setSizePolicy(sizePolicy)
        self.email_lineedit.setMinimumSize(QtCore.QSize(0, 0))
        self.email_lineedit.setStyleSheet("width: 400px;\n"
"height: 30px;\n"
"background-color: #e9e9e9;\n"
"border: 1px solid #828282;\n"
"border-radius: 8px;\n"
"font-family: Montserrat, sans-serif;\n"
"font-size: 1.3rem;\n"
"outline: none;\n"
"padding: 0 6px;")
        self.email_lineedit.setText("")
        self.email_lineedit.setObjectName("email_lineedit")
        self.email_layout.addWidget(self.email_lineedit)
        self.email_error_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.email_error_label.setStyleSheet("padding-left: 2px;\n"
"color: #a10e0e;")
        self.email_error_label.setObjectName("email_error_label")
        self.email_layout.addWidget(self.email_error_label)
        self.lineedits_layout.addLayout(self.email_layout)
        self.password_layout = QtWidgets.QVBoxLayout()
        self.password_layout.setSpacing(4)
        self.password_layout.setObjectName("password_layout")
        self.password_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.password_label.setStyleSheet("padding-left: 2px;\n"
"color: #5a5a5a;")
        self.password_label.setObjectName("password_label")
        self.password_layout.addWidget(self.password_label)
        self.password_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_lineedit.sizePolicy().hasHeightForWidth())
        self.password_lineedit.setSizePolicy(sizePolicy)
        self.password_lineedit.setMinimumSize(QtCore.QSize(0, 0))
        self.password_lineedit.setStyleSheet("width: 400px;\n"
"height: 30px;\n"
"background-color: #e9e9e9;\n"
"border: 1px solid #828282;\n"
"border-radius: 8px;\n"
"font-family: Montserrat, sans-serif;\n"
"font-size: 1.3rem;\n"
"outline: none;\n"
"padding: 0 6px;")
        self.password_lineedit.setText("")
        self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineedit.setObjectName("password_lineedit")
        self.password_layout.addWidget(self.password_lineedit)
        self.password_error_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.password_error_label.setEnabled(True)
        self.password_error_label.setStyleSheet("padding-left: 2px;\n"
"color: #a10e0e;")
        self.password_error_label.setObjectName("password_error_label")
        self.password_layout.addWidget(self.password_error_label)
        self.lineedits_layout.addLayout(self.password_layout)
        self.form_layout.addLayout(self.lineedits_layout)
        self.signin_btns_layout = QtWidgets.QVBoxLayout()
        self.signin_btns_layout.setSpacing(8)
        self.signin_btns_layout.setObjectName("signin_btns_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.signin_btns_layout.addItem(spacerItem)
        self.submit_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit_btn.sizePolicy().hasHeightForWidth())
        self.submit_btn.setSizePolicy(sizePolicy)
        self.submit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_btn.setStyleSheet("width: 400px;\n"
"border: none;\n"
"border-radius: 8px;\n"
"color: #fff;\n"
"outline: none;\n"
"padding: 8px 10px;\n"
"font-size: 1.5rem;\n"
"background-color: #7070ff;")
        self.submit_btn.setObjectName("submit_btn")
        self.signin_btns_layout.addWidget(self.submit_btn)
        self.phone_signin_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_signin_btn.sizePolicy().hasHeightForWidth())
        self.phone_signin_btn.setSizePolicy(sizePolicy)
        self.phone_signin_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.phone_signin_btn.setStyleSheet("width: 400px;\n"
"border: 1px solid #969696;\n"
"border-radius: 8px;\n"
"color: #8282ff;\n"
"outline: none;\n"
"padding: 8px 10px;\n"
"font-size: 1.5rem;")
        self.phone_signin_btn.setObjectName("phone_signin_btn")
        self.signin_btns_layout.addWidget(self.phone_signin_btn)
        self.email_signin_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_signin_btn.sizePolicy().hasHeightForWidth())
        self.email_signin_btn.setSizePolicy(sizePolicy)
        self.email_signin_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.email_signin_btn.setStyleSheet("width: 400px;\n"
"border: 1px solid #969696;\n"
"border-radius: 8px;\n"
"color: #8282ff;\n"
"outline: none;\n"
"padding: 8px 10px;\n"
"font-size: 1.5rem;")
        self.email_signin_btn.setObjectName("email_signin_btn")
        self.signin_btns_layout.addWidget(self.email_signin_btn)
        self.registration_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registration_btn.sizePolicy().hasHeightForWidth())
        self.registration_btn.setSizePolicy(sizePolicy)
        self.registration_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registration_btn.setStyleSheet("width: 400px;\n"
"border: 1px solid #969696;\n"
"border-radius: 8px;\n"
"color: #8282ff;\n"
"outline: none;\n"
"padding: 8px 10px;\n"
"font-size: 1.5rem;")
        self.registration_btn.setObjectName("registration_btn")
        self.signin_btns_layout.addWidget(self.registration_btn)
        self.form_layout.addLayout(self.signin_btns_layout)
        self.main_layout.addLayout(self.form_layout)
        self.profile_layout = QtWidgets.QVBoxLayout()
        self.profile_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.profile_layout.setContentsMargins(-1, 200, -1, 200)
        self.profile_layout.setSpacing(0)
        self.profile_layout.setObjectName("profile_layout")
        self.welcome_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_label.sizePolicy().hasHeightForWidth())
        self.welcome_label.setSizePolicy(sizePolicy)
        self.welcome_label.setStyleSheet("max-width: 424px;\n"
"color: #5a5a5a;\n"
"font-size: 18px;\n"
"font-weight: 700;")
        self.welcome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_label.setObjectName("welcome_label")
        self.profile_layout.addWidget(self.welcome_label)
        self.activation_code_layout = QtWidgets.QVBoxLayout()
        self.activation_code_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.activation_code_layout.setSpacing(8)
        self.activation_code_layout.setObjectName("activation_code_layout")
        self.activation_code_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activation_code_label.sizePolicy().hasHeightForWidth())
        self.activation_code_label.setSizePolicy(sizePolicy)
        self.activation_code_label.setAlignment(QtCore.Qt.AlignCenter)
        self.activation_code_label.setObjectName("activation_code_label")
        self.activation_code_layout.addWidget(self.activation_code_label)
        self.activation_code_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activation_code_lineedit.sizePolicy().hasHeightForWidth())
        self.activation_code_lineedit.setSizePolicy(sizePolicy)
        self.activation_code_lineedit.setMinimumSize(QtCore.QSize(0, 0))
        self.activation_code_lineedit.setStyleSheet("height: 30px;\n"
"background-color: #e9e9e9;\n"
"border: 1px solid #828282;\n"
"border-radius: 8px;\n"
"font-family: Montserrat, sans-serif;\n"
"font-size: 1.3rem;\n"
"outline: none;\n"
"padding: 0 6px;\n"
"margin: 0 auto;")
        self.activation_code_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.activation_code_lineedit.setObjectName("activation_code_lineedit")
        self.activation_code_layout.addWidget(self.activation_code_lineedit)
        self.profile_layout.addLayout(self.activation_code_layout)
        self.send_activation_email_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.send_activation_email_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_activation_email_btn.sizePolicy().hasHeightForWidth())
        self.send_activation_email_btn.setSizePolicy(sizePolicy)
        self.send_activation_email_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.send_activation_email_btn.setStyleSheet("max-width: 404px;\n"
"border: none;\n"
"border-radius: 8px;\n"
"color: #fff;\n"
"outline: none;\n"
"padding: 8px 10px;\n"
"font-size: 1.5rem;\n"
"background-color: #7070ff;")
        self.send_activation_email_btn.setObjectName("send_activation_email_btn")
        self.profile_layout.addWidget(self.send_activation_email_btn)
        self.main_layout.addLayout(self.profile_layout)
        self.main_layout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 454, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Authenticate App"))
        self.name_label.setText(_translate("MainWindow", "Name"))
        self.name_error_label.setText(_translate("MainWindow", "Error!"))
        self.surname_label.setText(_translate("MainWindow", "Surname"))
        self.surname_error_label.setText(_translate("MainWindow", "Error!"))
        self.phone_label.setText(_translate("MainWindow", "Phone number"))
        self.phone_error_label.setText(_translate("MainWindow", "Error!"))
        self.email_label.setText(_translate("MainWindow", "Email"))
        self.email_error_label.setText(_translate("MainWindow", "Error!"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.password_error_label.setText(_translate("MainWindow", "Error!"))
        self.submit_btn.setText(_translate("MainWindow", "Register"))
        self.phone_signin_btn.setText(_translate("MainWindow", "Authenticate with phone"))
        self.email_signin_btn.setText(_translate("MainWindow", "Authenticate with email"))
        self.registration_btn.setText(_translate("MainWindow", "Registration"))
        self.welcome_label.setText(_translate("MainWindow", "Welcome PLACEHOLDER!"))
        self.activation_code_label.setText(_translate("MainWindow", "Check your email and type in the activation code"))
        self.activation_code_lineedit.setInputMask(_translate("MainWindow", "999 999"))
        self.activation_code_lineedit.setText(_translate("MainWindow", " "))
        self.send_activation_email_btn.setText(_translate("MainWindow", "Send an account activation mail"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
